"""Add Jobs

Revision ID: 0312c0b796bb
Revises: 195fb832cd33
Create Date: 2022-02-07 11:06:02.775210

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0312c0b796bb'
down_revision = '195fb832cd33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('startdate', sa.String(), nullable=True),
    sa.Column('enddate', sa.String(), nullable=True),
    sa.Column('current_job', sa.Boolean(), nullable=True),
    sa.Column('profile_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['userprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_company'), 'job', ['company'], unique=False)
    op.create_index(op.f('ix_job_designation'), 'job', ['designation'], unique=False)
    op.create_index(op.f('ix_job_id'), 'job', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_id'), table_name='job')
    op.drop_index(op.f('ix_job_designation'), table_name='job')
    op.drop_index(op.f('ix_job_company'), table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###
