"""Update Certification Model

Revision ID: 098a88825606
Revises: 152d57e683a2
Create Date: 2022-02-09 00:52:11.753897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '098a88825606'
down_revision = '152d57e683a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
