"""Add is premium

Revision ID: 13cd5edfd2ea
Revises: 082d1aa30f29
Create Date: 2022-02-12 00:15:05.119943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13cd5edfd2ea'
down_revision = '082d1aa30f29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_premium', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_premium')
    # ### end Alembic commands ###
