"""Update Certification Model

Revision ID: 152d57e683a2
Revises: 1610cad5a18f
Create Date: 2022-02-09 00:51:03.859660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '152d57e683a2'
down_revision = '1610cad5a18f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
