"""Profile Public Name

Revision ID: 1610cad5a18f
Revises: 5468745e67c8
Create Date: 2022-02-07 14:53:43.346795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1610cad5a18f'
down_revision = '5468745e67c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userprofile', sa.Column('public_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userprofile', 'public_name')
    # ### end Alembic commands ###
