"""Add Education

Revision ID: 1a66c3a917fd
Revises: 0312c0b796bb
Create Date: 2022-02-07 11:17:46.746675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1a66c3a917fd'
down_revision = '0312c0b796bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('current', sa.Boolean(), nullable=True),
    sa.Column('college', sa.String(), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('startdate', sa.String(), nullable=True),
    sa.Column('enddate', sa.String(), nullable=True),
    sa.Column('profile_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['userprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_college'), 'education', ['college'], unique=False)
    op.create_index(op.f('ix_education_id'), 'education', ['id'], unique=False)
    op.add_column('job', sa.Column('current', sa.Boolean(), nullable=True))
    op.drop_column('job', 'current_job')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('current_job', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('job', 'current')
    op.drop_index(op.f('ix_education_id'), table_name='education')
    op.drop_index(op.f('ix_education_college'), table_name='education')
    op.drop_table('education')
    # ### end Alembic commands ###
