"""add website

Revision ID: 37ab82c7afd1
Revises: cd96ea17372b
Create Date: 2022-03-02 13:41:28.852381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37ab82c7afd1'
down_revision = 'cd96ea17372b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userprofile', sa.Column('website', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userprofile', 'website')
    # ### end Alembic commands ###
