"""Add Certifications

Revision ID: 5468745e67c8
Revises: 1a66c3a917fd
Create Date: 2022-02-07 11:35:32.856662

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5468745e67c8'
down_revision = '1a66c3a917fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certification',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('current', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('issuing_organization', sa.String(), nullable=True),
    sa.Column('issue_date', sa.String(), nullable=True),
    sa.Column('expiration_date', sa.String(), nullable=True),
    sa.Column('credential_id', sa.String(), nullable=True),
    sa.Column('credential_url', sa.String(), nullable=True),
    sa.Column('profile_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['userprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certification_id'), 'certification', ['id'], unique=False)
    op.create_index(op.f('ix_certification_name'), 'certification', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_certification_name'), table_name='certification')
    op.drop_index(op.f('ix_certification_id'), table_name='certification')
    op.drop_table('certification')
    # ### end Alembic commands ###
