"""Change DateTime to Epoch

Revision ID: b295004d71d8
Revises: 13cd5edfd2ea
Create Date: 2022-02-12 02:40:05.329909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b295004d71d8'
down_revision = '13cd5edfd2ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
