"""Removed unnecesary theme

Revision ID: cd96ea17372b
Revises: a3192f683f9e
Create Date: 2022-02-23 09:27:15.733006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cd96ea17372b"
down_revision = "a3192f683f9e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("userprofile", "theme")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "userprofile",
        sa.Column("theme", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
